Revamp README.md
alex1701c/EmojiRunner pull request #6
Opened 2022-02-16 20:34 UTC by QazCetelic

2022-02-19 08:50 UTC, alex1701c commented
Generally speaking, I wonder if there is even a point in repeating the instructions from the install.sh script in the readme.

What do you think about showing the clone command + command to execute the install script instead?

2022-02-20 09:15 UTC, QazCetelic commented
Maybe it's better to leave the manual method out, the first option should suffice.

2022-02-26 08:37 UTC, alex1701c requested changes
Two neatpicks, then this is good to go :)

2022-02-26 08:37 UTC, alex1701c commented on README.md
>  mkdir build
This is not needed when one uses the install script

2022-02-26 08:37 UTC, alex1701c commented on README.md
> +<details>
TBH I would not use the summary here, because the install instructions are pretty short and important information for readers

2022-02-26 20:15 UTC, QazCetelic commented
Changed it, anything else?

2022-02-26 20:42 UTC, alex1701c commented on README.md
>  mkdir build
I only meant the `mkdir build` line, not the rest of the bash snippet

2022-03-02 12:42 UTC, alex1701c commented
May I squash the commits when merging?

2022-03-02 12:42 UTC, alex1701c approved these changes

2022-03-03 07:40 UTC, merged